#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 使用git commit提交代码的是，会去执行pnpm commitlint，去校验commit后面的提交信息规范
# 当我们 commit 提交信息时，就不能再随意写了，必须是 git commit -m 'fix: xxx' 符合类型的才可以，
# 需要注意的是类型的后面需要用英文的 :，并且冒号后面是需要空一格的，这个是不能省略的
pnpm commitlint
